import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..', 'core', 'src', 'main', 'java', 'dev', 'valarisclient', 'core', 'modules')
const en = {}
const fr = {}

const frDesc = {
  'Shows your framerate': 'Affiche votre framerate',
  'Shows your WASD and mouse inputs': 'Affiche vos entrées WASD et souris',
  'Shows your clicks per second': 'Affiche vos clics par seconde',
  'Shows your server latency': 'Affiche la latence serveur',
  'Tracks consecutive hits without taking damage': 'Compte les coups consécutifs sans subir de dégâts',
  "Shows your current target's name and health": 'Affiche le nom et les PV de votre cible',
  'Shows your armor durability': 'Affiche la durabilité de votre armure',
  'Lists your active potion effects': 'Liste vos effets de potion actifs',
  'Shows your attack cooldown progress': 'Affiche la progression de la recharge d\'attaque',
  'Premium customizable crosshair': 'Réticule personnalisable premium',
  'Changes the color shown when you hit an entity': 'Change la couleur affichée quand vous touchez une entité',
  'Custom particles on hit only': 'Particules personnalisées à l\'impact uniquement',
  'Shows damage taken as floating text': 'Affiche les dégâts reçus en texte flottant',
  'Shows which direction you are facing': 'Affiche la direction vers laquelle vous regardez',
  'Shows your block position': 'Affiche votre position en blocs',
  'Apply LOW, MEDIUM, or HIGH presets': 'Applique les préréglages FAIBLE, MOYEN ou ÉLEVÉ',
  'Boosts render distance for quicker chunk loading': 'Augmente la distance de rendu pour charger les chunks plus vite',
  'Disables fancy graphics': 'Désactive les graphismes avancés',
  'Reduces simulation distance': 'Réduit la distance de simulation',
  'Lowers max FPS when unfocused': 'Réduit le FPS max quand la fenêtre n\'est pas active',
  'Suggests garbage collection periodically': 'Suggère le garbage collection périodiquement',
  'Shows used and max memory': 'Affiche la mémoire utilisée et max',
  'Sets particles to minimal': 'Met les particules au minimum',
  'Lowers entity render distance': 'Réduit la distance de rendu des entités',
  'Lowers render distance, clouds, and particles': 'Réduit distance de rendu, nuages et particules',
  'Shows hovered item details in HUD': 'Affiche les détails de l\'objet survolé dans le HUD',
  'Improves chat readability': 'Améliore la lisibilité du chat',
  'Quick-connect to a saved server': 'Connexion rapide à un serveur enregistré',
  'Highlights items matching your search term': 'Surligne les objets correspondant à votre recherche',
  'Shows shulker contents on hover': 'Affiche le contenu du shulker au survol',
  'Shows your held item count': 'Affiche le nombre d\'objets en main',
  'Shows distance to your last death': 'Affiche la distance jusqu\'à votre dernière mort',
  'Shows distance and direction to a saved waypoint': 'Affiche distance et direction vers un point enregistré',
  'Hides chat messages with blocked words': 'Masque les messages contenant des mots bloqués',
  'Prefix incoming chat with timestamps': 'Préfixe le chat entrant avec l\'heure',
  'Says gg when a game ends': 'Dit gg quand une partie se termine',
  'Respawn automatically when you die': 'Réapparaît automatiquement à la mort',
  'Stay sneaking while enabled': 'Reste accroupi tant que le module est actif',
  'Sprint automatically while moving forward': 'Sprinte automatiquement en avançant',
  'Hold C to zoom the camera': 'Maintenir C pour zoomer la caméra',
  'Smooths camera movement for recordings': 'Adoucit les mouvements de caméra pour l\'enregistrement',
  'Hides the HUD for clean screenshots': 'Masque le HUD pour des captures propres',
  'Hides coordinates and branding for streams': 'Masque coordonnées et branding pour le stream',
  'Hold V to zoom the camera for shots': 'Maintenir V pour zoomer la caméra (captures)',
  'Record and replay movement': 'Enregistre et rejoue les déplacements',
  'Export MP4 clips to config/valarisclient/clips': 'Exporte des clips MP4 vers config/valarisclient/clips',
  'Clean Rich Presence with server context and compact stats': 'Rich Presence avec contexte serveur et stats compactes',
  'Shows your name and session time': 'Affiche votre nom et la durée de session',
  'Customize your client appearance': 'Personnalise l\'apparence du client',
  'Sync configs with ValarisCloud': 'Synchronise les configs avec ValarisCloud',
  'Opens the ClickGUI for module settings': 'Ouvre le ClickGUI pour les réglages de modules',
  'Switch between default, PvP, and survival configs': 'Bascule entre configs équilibré, PvP et survie'
}

function walk(dir) {
  for (const file of fs.readdirSync(dir)) {
    const full = path.join(dir, file)
    if (fs.statSync(full).isDirectory()) {
      walk(full)
      continue
    }
    if (!file.endsWith('Module.java')) continue
    const text = fs.readFileSync(full, 'utf8')
    const match = text.match(/super\("([^"]+)",\s*"([^"]+)",\s*"([^"]*)"/)
    if (!match) continue
    const [, id, name, desc] = match
    const key = id.replace(/-/g, '_')
    en[`valaris.module.${key}.name`] = name
    en[`valaris.module.${key}.description`] = desc
    fr[`valaris.module.${key}.name`] = name
    fr[`valaris.module.${key}.description`] = frDesc[desc] ?? desc
  }
}

walk(root)

Object.assign(en, {
  'valaris.category.pvp': 'PvP',
  'valaris.category.performance': 'Performance',
  'valaris.category.qol': 'QoL',
  'valaris.category.creator': 'Creator',
  'valaris.category.valaris': 'Valaris',
  'valaris.gui.main_menu.resume': 'Resume',
  'valaris.gui.main_menu.modules': 'Modules',
  'valaris.gui.main_menu.hud_editor': 'HUD Editor',
  'valaris.gui.main_menu.configurations': 'Configurations',
  'valaris.gui.main_menu.cosmetics': 'Cosmetics',
  'valaris.gui.main_menu.settings': 'Settings',
  'valaris.gui.main_menu.version': 'Valaris%s',
  'valaris.gui.main_menu.hint': 'Right Shift  ·  H = HUD',
  'valaris.gui.title.singleplayer': 'Singleplayer',
  'valaris.gui.title.multiplayer': 'Multiplayer',
  'valaris.gui.title.valaris_client': 'ValarisClient',
  'valaris.gui.title.options': 'Options',
  'valaris.gui.title.quit': 'Quit Game',
  'valaris.gui.title.footer': 'ValarisClient %1$s  ·  Minecraft %2$s',
  'valaris.gui.clickgui.favorites': 'Favorites',
  'valaris.gui.clickgui.search.placeholder': 'Type to search...',
  'valaris.gui.clickgui.search.panel': 'Search (%d)',
  'valaris.gui.settings.title': 'Settings',
  'valaris.gui.settings.search.placeholder': 'Search settings...',
  'valaris.gui.settings.tab.general': 'General',
  'valaris.gui.settings.tab.appearance': 'Appearance',
  'valaris.gui.settings.tab.performance': 'Performance',
  'valaris.gui.settings.tab.controls': 'Controls',
  'valaris.gui.settings.tab.account': 'Account',
  'valaris.gui.settings.tab.privacy': 'Privacy',
  'valaris.gui.settings.tab.about': 'About',
  'valaris.gui.settings.row.profile': 'Profile',
  'valaris.gui.settings.row.minecraft': 'Minecraft',
  'valaris.gui.settings.row.cloud_sync': 'Cloud sync',
  'valaris.gui.settings.cloud_sync.enabled': 'Enabled',
  'valaris.gui.settings.cloud_sync.disabled': 'Disabled',
  'valaris.gui.settings.row.active_theme': 'Active theme',
  'valaris.gui.settings.theme.dark': 'ValarisDark',
  'valaris.gui.settings.theme.light': 'ValarisLight',
  'valaris.gui.settings.row.tip': 'Tip',
  'valaris.gui.settings.tip.performance': 'Use Performance Profiles module',
  'valaris.gui.settings.row.clickgui': 'ClickGUI',
  'valaris.gui.settings.controls.hint': 'Right Shift · HUD Editor: H',
  'valaris.gui.settings.row.player': 'Player',
  'valaris.gui.settings.row.valaris_account': 'ValarisAccount',
  'valaris.gui.settings.account.hint': 'Connect via ValarisAccount module',
  'valaris.gui.settings.row.data': 'Data',
  'valaris.gui.settings.privacy.hint': 'Configs stored locally only',
  'valaris.gui.settings.about.client': 'ValarisClient',
  'valaris.gui.settings.about.version': 'v%s',
  'valaris.gui.settings.about.legitimate': 'Legitimate client',
  'valaris.gui.settings.about.tagline': 'Visual & QoL only',
  'valaris.gui.onboarding.step_footer': 'Step %1$d/4  ·  Esc = skip',
  'valaris.gui.onboarding.theme.title': 'Choose your theme',
  'valaris.gui.onboarding.theme.hint': 'Click an option then continue',
  'valaris.gui.onboarding.theme.continue': 'Continue',
  'valaris.gui.onboarding.profile.title': 'Module profile',
  'valaris.gui.onboarding.profile.balanced': 'Balanced',
  'valaris.gui.onboarding.profile.pvp': 'PvP',
  'valaris.gui.onboarding.profile.survival': 'Survival',
  'valaris.gui.onboarding.profile.hint': 'FPS, coords, crosshair, Discord RPC included',
  'valaris.gui.onboarding.keybinds.title': 'Essential shortcuts',
  'valaris.gui.onboarding.keybinds.menu': 'Right Shift  →  ValarisMenu (modules, settings)',
  'valaris.gui.onboarding.keybinds.hud': 'H  →  HUD Editor (move elements)',
  'valaris.gui.onboarding.keybinds.zoom': 'C  →  Zoom (Zoom module, hold)',
  'valaris.gui.onboarding.keybinds.got_it': 'Got it!',
  'valaris.gui.onboarding.finish.title': "You're all set!",
  'valaris.gui.onboarding.finish.line1': 'Your HUD, crosshair and Discord RPC are ready.',
  'valaris.gui.onboarding.finish.line2': 'Explore Modules in the menu to customize everything.',
  'valaris.gui.onboarding.finish.enter': 'Enter ValarisClient',
  'valaris.gui.cosmetics.title': 'Cosmetics',
  'valaris.gui.cosmetics.footer': 'Click to equip · Scroll for more',
  'valaris.gui.configurations.title': 'Configurations',
  'valaris.gui.configurations.profile': 'Profile: %s',
  'valaris.gui.configurations.auto_sync': 'Auto sync: %s',
  'valaris.gui.configurations.on': 'ON',
  'valaris.gui.configurations.off': 'OFF',
  'valaris.gui.configurations.versions': 'Versions (%d):',
  'valaris.gui.configurations.footer': 'U=upload  D=download  Modules → ValarisConfig Cloud',
  'valaris.gui.loading.core': 'Loading Core...',
  'valaris.gui.loading.modules': 'Loading Modules...',
  'valaris.gui.loading.ready': 'ValarisClient ready',
  'valaris.gui.loading.tagline': 'Premium Minecraft Client',
  'valaris.gui.loading.version': 'v%s',
  'valaris.notification.module.enabled': 'Enabled',
  'valaris.notification.module.disabled': 'Disabled',
  'valaris.discord.singleplayer': 'Singleplayer',
  'valaris.discord.playing_on': 'Playing on %s',
  'valaris.discord.modules_count': '%1$d/%2$d modules',
  'valaris.discord.fps': '%d FPS',
  'valaris.discord.client_version': 'ValarisClient v%s',
  'valaris.discord.browsing_menus': 'Browsing menus',
  'valaris.discord.main_menu': 'In Main Menu',
  'valaris.discord.state_menu': '%1$s · Minecraft %2$s · Valarisv%3$s',
  'valaris.discord.main_menu_small': 'Main Menu',
  'valaris.discord.player_fallback': 'Player',
  'valaris.discord.button.client': 'ValarisClient',
  'valaris.discord.button.discord_app': 'Discord App',
  'valaris.discord.button.server_status': 'Server Status',
  'valaris.hud.fps.format': '%d FPS',
  'valaris.hud.coordinates.format': 'X: %d Y: %d Z: %d',
  'valaris.hud.cps.format': '%1$d | %2$d CPS',
  'valaris.hud.ping.format': '%d ms',
  'valaris.hud.keystroke.lmb': 'LMB',
  'valaris.hud.keystroke.rmb': 'RMB',
  'valaris.hud.watermark': 'Watermark',
  'valaris.hud.notifications': 'Notifications',
  'valaris.hud.fps': 'FPS Counter',
  'valaris.hud.coordinates': 'Coordinates',
  'valaris.hud.cps': 'CPS Counter',
  'valaris.hud.ping': 'Ping Display',
  'valaris.hud.keystrokes': 'Keystrokes',
  'valaris.hud.target': 'Target HUD',
  'valaris.hud.combo': 'Combo Counter',
  'valaris.hud.damage': 'Damage Indicator',
  'valaris.hud.direction': 'Direction HUD',
  'valaris.hud.armor': 'Armor HUD',
  'valaris.hud.potions': 'Potion HUD',
  'valaris.hud.cooldown': 'Item Cooldown',
  'valaris.hud.crosshair': 'Crosshair',
  'valaris.hud.crosshair_preview': 'Crosshair Preview',
  'valaris.hud.memory': 'Memory Monitor',
  'valaris.hud.valaris_account': 'ValarisAccount',
  'valaris.hud.better_tooltips': 'Better Tooltips',
  'valaris.hud.server_switcher': 'Server Switcher',
  'valaris.hud.inventory_search': 'Inventory Search',
  'valaris.hud.shulker_preview': 'Shulker Preview',
  'valaris.hud.item_counter': 'Item Counter',
  'valaris.hud.death_waypoint': 'Death Waypoint',
  'valaris.hud.waypoints': 'Waypoints',
  'valaris.hud.clip_recorder_overlay': 'Clip Recorder Overlay',
  'valaris.hud.replay_overlay': 'Replay Overlay',
  'valaris.hud.cinematic_indicator': 'Cinematic Indicator',
  'valaris.enum.perf_profile.low': 'Low',
  'valaris.enum.perf_profile.medium': 'Medium',
  'valaris.enum.perf_profile.high': 'High',
  'valaris.enum.config_profile.default': 'Default',
  'valaris.enum.config_profile.pvp': 'PvP',
  'valaris.enum.config_profile.survival': 'Survival',
  'valaris.enum.cosmetic_type.cape': 'Cape',
  'valaris.enum.cosmetic_type.wings': 'Wings',
  'valaris.enum.cosmetic_type.hat': 'Hat',
  'valaris.enum.cosmetic_type.particles': 'Particles',
  'valaris.enum.cosmetic_type.badge': 'Badge',
  'valaris.enum.rarity.common': 'Common',
  'valaris.enum.rarity.rare': 'Rare',
  'valaris.enum.rarity.epic': 'Epic',
  'valaris.enum.rarity.legendary': 'Legendary'
})

Object.assign(fr, {
  'valaris.category.creator': 'Créateur',
  'valaris.gui.main_menu.resume': 'Reprendre',
  'valaris.gui.main_menu.modules': 'Modules',
  'valaris.gui.main_menu.hud_editor': 'Éditeur HUD',
  'valaris.gui.main_menu.configurations': 'Configurations',
  'valaris.gui.main_menu.cosmetics': 'Cosmétiques',
  'valaris.gui.main_menu.settings': 'Réglages',
  'valaris.gui.main_menu.version': 'Valaris%s',
  'valaris.gui.main_menu.hint': 'Right Shift  ·  H = HUD',
  'valaris.gui.title.singleplayer': 'Solo',
  'valaris.gui.title.multiplayer': 'Multijoueur',
  'valaris.gui.title.valaris_client': 'ValarisClient',
  'valaris.gui.title.options': 'Options',
  'valaris.gui.title.quit': 'Quitter',
  'valaris.gui.title.footer': 'ValarisClient %1$s  ·  Minecraft %2$s',
  'valaris.gui.clickgui.favorites': 'Favoris',
  'valaris.gui.clickgui.search.placeholder': 'Tapez pour rechercher…',
  'valaris.gui.clickgui.search.panel': 'Recherche (%d)',
  'valaris.gui.settings.title': 'Réglages',
  'valaris.gui.settings.search.placeholder': 'Rechercher dans les réglages…',
  'valaris.gui.settings.tab.general': 'Général',
  'valaris.gui.settings.tab.appearance': 'Apparence',
  'valaris.gui.settings.tab.performance': 'Performance',
  'valaris.gui.settings.tab.controls': 'Contrôles',
  'valaris.gui.settings.tab.account': 'Compte',
  'valaris.gui.settings.tab.privacy': 'Confidentialité',
  'valaris.gui.settings.tab.about': 'À propos',
  'valaris.gui.settings.row.profile': 'Profil',
  'valaris.gui.settings.row.minecraft': 'Minecraft',
  'valaris.gui.settings.row.cloud_sync': 'Sync cloud',
  'valaris.gui.settings.cloud_sync.enabled': 'Activé',
  'valaris.gui.settings.cloud_sync.disabled': 'Désactivé',
  'valaris.gui.settings.row.active_theme': 'Thème actif',
  'valaris.gui.settings.theme.dark': 'ValarisSombre',
  'valaris.gui.settings.theme.light': 'ValarisClair',
  'valaris.gui.settings.row.tip': 'Astuce',
  'valaris.gui.settings.tip.performance': 'Utilisez le module Profils de performance',
  'valaris.gui.settings.row.clickgui': 'ClickGUI',
  'valaris.gui.settings.controls.hint': 'Right Shift · Éditeur HUD : H',
  'valaris.gui.settings.row.player': 'Joueur',
  'valaris.gui.settings.row.valaris_account': 'Compte Valaris',
  'valaris.gui.settings.account.hint': 'Connectez-vous via le module Compte Valaris',
  'valaris.gui.settings.row.data': 'Données',
  'valaris.gui.settings.privacy.hint': 'Configs stockées localement uniquement',
  'valaris.gui.settings.about.client': 'ValarisClient',
  'valaris.gui.settings.about.version': 'v%s',
  'valaris.gui.settings.about.legitimate': 'Client légitime',
  'valaris.gui.settings.about.tagline': 'Visuel et QoL uniquement',
  'valaris.gui.onboarding.step_footer': 'Étape %1$d/4  ·  Échap = passer',
  'valaris.gui.onboarding.theme.title': 'Choisis ton thème',
  'valaris.gui.onboarding.theme.hint': 'Clique une option puis continue',
  'valaris.gui.onboarding.theme.continue': 'Continuer',
  'valaris.gui.onboarding.profile.title': 'Profil de modules',
  'valaris.gui.onboarding.profile.balanced': 'Équilibré',
  'valaris.gui.onboarding.profile.pvp': 'PvP',
  'valaris.gui.onboarding.profile.survival': 'Survie',
  'valaris.gui.onboarding.profile.hint': 'FPS, coords, crosshair, Discord RPC inclus',
  'valaris.gui.onboarding.keybinds.title': 'Raccourcis essentiels',
  'valaris.gui.onboarding.keybinds.menu': 'Right Shift  →  Menu Valaris(modules, réglages)',
  'valaris.gui.onboarding.keybinds.hud': 'H  →  HUD Editor (déplacer les éléments)',
  'valaris.gui.onboarding.keybinds.zoom': 'C  →  Zoom (module Zoom, maintenir)',
  'valaris.gui.onboarding.keybinds.got_it': 'Compris !',
  'valaris.gui.onboarding.finish.title': "C'est parti !",
  'valaris.gui.onboarding.finish.line1': 'Ton HUD, crosshair et Discord RPC sont prêts.',
  'valaris.gui.onboarding.finish.line2': 'Explore Modules dans le menu pour tout personnaliser.',
  'valaris.gui.onboarding.finish.enter': 'Entrer dans ValarisClient',
  'valaris.gui.cosmetics.title': 'Cosmétiques',
  'valaris.gui.cosmetics.footer': 'Cliquer pour équiper · Défiler pour plus',
  'valaris.gui.configurations.title': 'Configurations',
  'valaris.gui.configurations.profile': 'Profil : %s',
  'valaris.gui.configurations.auto_sync': 'Sync auto : %s',
  'valaris.gui.configurations.on': 'ON',
  'valaris.gui.configurations.off': 'OFF',
  'valaris.gui.configurations.versions': 'Versions (%d) :',
  'valaris.gui.configurations.footer': 'U=upload  D=download  Modules → ValarisConfig Cloud',
  'valaris.gui.loading.core': 'Chargement du noyau…',
  'valaris.gui.loading.modules': 'Chargement des modules…',
  'valaris.gui.loading.ready': 'ValarisClient prêt',
  'valaris.gui.loading.tagline': 'Client Minecraft premium',
  'valaris.gui.loading.version': 'v%s',
  'valaris.notification.module.enabled': 'Activé',
  'valaris.notification.module.disabled': 'Désactivé',
  'valaris.discord.singleplayer': 'Solo',
  'valaris.discord.playing_on': 'Joue sur %s',
  'valaris.discord.modules_count': '%1$d/%2$d modules',
  'valaris.discord.fps': '%d FPS',
  'valaris.discord.client_version': 'ValarisClient v%s',
  'valaris.discord.browsing_menus': 'Parcourt les menus',
  'valaris.discord.main_menu': 'Dans le menu principal',
  'valaris.discord.state_menu': '%1$s · Minecraft %2$s · Valarisv%3$s',
  'valaris.discord.main_menu_small': 'Menu principal',
  'valaris.discord.player_fallback': 'Joueur',
  'valaris.discord.button.client': 'ValarisClient',
  'valaris.discord.button.discord_app': 'Application Discord',
  'valaris.discord.button.server_status': 'Statut du serveur',
  'valaris.hud.fps.format': '%d FPS',
  'valaris.hud.coordinates.format': 'X: %d Y: %d Z: %d',
  'valaris.hud.cps.format': '%1$d | %2$d CPS',
  'valaris.hud.ping.format': '%d ms',
  'valaris.hud.keystroke.lmb': 'Clic G',
  'valaris.hud.keystroke.rmb': 'Clic D',
  'valaris.hud.watermark': 'Filigrane',
  'valaris.hud.notifications': 'Notifications',
  'valaris.hud.fps': 'Compteur FPS',
  'valaris.hud.coordinates': 'Coordonnées',
  'valaris.hud.cps': 'Compteur CPS',
  'valaris.hud.ping': 'Affichage du ping',
  'valaris.hud.keystrokes': 'Touches',
  'valaris.hud.target': 'HUD de cible',
  'valaris.hud.combo': 'Compteur de combo',
  'valaris.hud.damage': 'Indicateur de dégâts',
  'valaris.hud.direction': 'HUD de direction',
  'valaris.hud.armor': 'HUD d\'armure',
  'valaris.hud.potions': 'HUD de potions',
  'valaris.hud.cooldown': 'Recharge d\'attaque',
  'valaris.hud.crosshair': 'Réticule',
  'valaris.hud.crosshair_preview': 'Aperçu du réticule',
  'valaris.hud.memory': 'Moniteur mémoire',
  'valaris.hud.valaris_account': 'Compte Valaris',
  'valaris.hud.better_tooltips': 'Infobulles améliorées',
  'valaris.hud.server_switcher': 'Sélecteur de serveur',
  'valaris.hud.inventory_search': 'Recherche d\'inventaire',
  'valaris.hud.shulker_preview': 'Aperçu de shulker',
  'valaris.hud.item_counter': 'Compteur d\'objets',
  'valaris.hud.death_waypoint': 'Point de mort',
  'valaris.hud.waypoints': 'Points de passage',
  'valaris.hud.clip_recorder_overlay': 'Overlay enregistreur',
  'valaris.hud.replay_overlay': 'Overlay replay',
  'valaris.hud.cinematic_indicator': 'Indicateur cinématique',
  'valaris.enum.perf_profile.low': 'Faible',
  'valaris.enum.perf_profile.medium': 'Moyen',
  'valaris.enum.perf_profile.high': 'Élevé',
  'valaris.enum.config_profile.default': 'Équilibré',
  'valaris.enum.config_profile.pvp': 'PvP',
  'valaris.enum.config_profile.survival': 'Survie',
  'valaris.enum.cosmetic_type.cape': 'Cape',
  'valaris.enum.cosmetic_type.wings': 'Ailes',
  'valaris.enum.cosmetic_type.hat': 'Chapeau',
  'valaris.enum.cosmetic_type.particles': 'Particules',
  'valaris.enum.cosmetic_type.badge': 'Badge',
  'valaris.enum.rarity.common': 'Commun',
  'valaris.enum.rarity.rare': 'Rare',
  'valaris.enum.rarity.epic': 'Épique',
  'valaris.enum.rarity.legendary': 'Légendaire'
})

for (const key of Object.keys(en)) {
  if (key.startsWith('valaris.module.') && key.endsWith('.name') && !fr[key]) {
    fr[key] = en[key]
  }
}

const targets = [
  'mc-1.21.11/src/main/resources/assets/valarisclient/lang',
  'mc-26.2/src/main/resources/assets/valarisclient/lang'
]

for (const rel of targets) {
  const dir = path.join(__dirname, '..', rel)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, 'en_us.json'), JSON.stringify(en, null, 2))
  fs.writeFileSync(path.join(dir, 'fr_fr.json'), JSON.stringify(fr, null, 2))
}

console.log(`Generated ${Object.keys(en).length} EN keys and ${Object.keys(fr).length} FR keys`)
