const { contextBridge, ipcRenderer, clipboard } = require("electron");

contextBridge.exposeInMainWorld("valaris", {
  getState: () => ipcRenderer.invoke("state:get"),
  getVersions: () => ipcRenderer.invoke("versions:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:update", settings),
  chooseJava: () => ipcRenderer.invoke("dialog:java"),
  chooseFolder: () => ipcRenderer.invoke("dialog:folder"),
  openFolder: (folder) => ipcRenderer.invoke("folder:open", folder),
  saveProfile: (profile) => ipcRenderer.invoke("profiles:save", profile),
  deleteProfile: (id) => ipcRenderer.invoke("profiles:delete", id),
  activateProfile: (id) => ipcRenderer.invoke("profiles:activate", id),
  saveServer: (server) => ipcRenderer.invoke("servers:save", server),
  deleteServer: (id) => ipcRenderer.invoke("servers:delete", id),
  addOfflineAccount: (username) => ipcRenderer.invoke("accounts:add-offline", username),
  deleteAccount: (id) => ipcRenderer.invoke("accounts:delete", id),
  activateAccount: (id) => ipcRenderer.invoke("accounts:activate", id),
  beginMicrosoftLogin: () => ipcRenderer.invoke("auth:microsoft-begin"),
  openExternal: (url) => ipcRenderer.invoke("external:open", url),
  copyText: (value) => clipboard.writeText(String(value)),
  install: (id) => ipcRenderer.invoke("minecraft:install", id),
  launch: (id, serverAddress) => ipcRenderer.invoke("minecraft:launch", id, serverAddress),
  isInstalled: (id) => ipcRenderer.invoke("minecraft:is-installed", id),
  searchModpacks: (query) => ipcRenderer.invoke("modpacks:search", query),
  getModpackVersions: (projectId) => ipcRenderer.invoke("modpacks:versions", projectId),
  installModpack: (project) => ipcRenderer.invoke("modpacks:install", project),
  getPartnerServers: () => ipcRenderer.invoke("partners:get"),
  checkUpdates: () => ipcRenderer.invoke("updates:check"),
  skipUpdate: (version) => ipcRenderer.invoke("updates:skip", version),
  downloadAndRunUpdate: (update) => ipcRenderer.invoke("updates:download-run", update),
  clearCache: () => ipcRenderer.invoke("cache:clear"),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  maximize: () => ipcRenderer.invoke("window:maximize"),
  close: () => ipcRenderer.invoke("window:close"),
  onProgress: (callback) => ipcRenderer.on("minecraft:progress", (_, value) => callback(value)),
  onAuthStatus: (callback) => ipcRenderer.on("auth:status", (_, value) => callback(value)),
  onAuthComplete: (callback) => ipcRenderer.on("auth:complete", (_, value) => callback(value)),
  onDiscordStatus: (callback) => ipcRenderer.on("discord:status", (_, value) => callback(value))
});
